[build]
  command = "npm run build"  # Command to build the project
  publish = "dist"  # Folder to publish the build output (make sure this matches your actual output directory)
  functions = "netlify/functions"  # Directory for Netlify functions
  node_bundler = "esbuild"  # Bundler for Node.js functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  # Redirect all routes to the index.html for Single Page Application (SPA) routing

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200  # Make sure this works for your serverless functions

[functions]
  node_bundler = "esbuild"  # Bundler for Node.js functions
  external_node_modules = ["@netlify/functions"]  # Add external Node.js modules needed in your functions

[[headers]]
  for = "/*"  # Apply these headers globally
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, OPTIONS"
  Access-Control-Allow-Headers = "Content-Type"
